"""baseline

Revision ID: d4ed0263421d
Revises: 6a9c302217f7
Create Date: 2025-11-05 23:59:09.792415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ed0263421d'
down_revision: Union[str, Sequence[str], None] = '6a9c302217f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('cat_api_data', sa.Column('timestamp', sa.String(), nullable=False))
    op.add_column('cat_api_data', sa.Column('latency', sa.Float(), nullable=False))
    op.add_column('cat_api_data', sa.Column('failed_request', sa.Boolean(), nullable=False))
    op.add_column('cat_api_data', sa.Column('length_correct', sa.Boolean(), nullable=False))
    op.add_column('cat_api_data', sa.Column('punctuation', sa.Boolean(), nullable=False))
    op.add_column('cat_api_data', sa.Column('api_fact', sa.Text(), nullable=False))
    op.add_column('cat_api_data', sa.Column('api_length', sa.Integer(), nullable=False))
    op.drop_column('cat_api_data', 'data')
    op.drop_column('cat_api_data', 'num')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat_api_data', sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cat_api_data', sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cat_api_data', 'api_length')
    op.drop_column('cat_api_data', 'api_fact')
    op.drop_column('cat_api_data', 'punctuation')
    op.drop_column('cat_api_data', 'length_correct')
    op.drop_column('cat_api_data', 'failed_request')
    op.drop_column('cat_api_data', 'latency')
    op.drop_column('cat_api_data', 'timestamp')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    # ### end Alembic commands ###
