"""baseline

Revision ID: db7e4e94059b
Revises: 6a9c302217f7
Create Date: 2025-11-06 00:17:08.338793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e4e94059b'
down_revision: Union[str, Sequence[str], None] = '6a9c302217f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_api_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('failed_request', sa.Boolean(), nullable=False),
    sa.Column('length_correct', sa.Boolean(), nullable=False),
    sa.Column('punctuation', sa.Boolean(), nullable=False),
    sa.Column('api_fact', sa.Text(), nullable=False),
    sa.Column('api_length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat_api_data')
    # ### end Alembic commands ###
